/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XAutoplayToggle {
        "autoplay": boolean;
    }
    interface XPreferencesButton {
        "icon": string;
    }
    interface XPreferencesList {
    }
    interface XSoundToggle {
        "muted": boolean;
    }
    interface XThemeToggle {
    }
}
declare global {
    interface HTMLXAutoplayToggleElement extends Components.XAutoplayToggle, HTMLStencilElement {
    }
    var HTMLXAutoplayToggleElement: {
        prototype: HTMLXAutoplayToggleElement;
        new (): HTMLXAutoplayToggleElement;
    };
    interface HTMLXPreferencesButtonElement extends Components.XPreferencesButton, HTMLStencilElement {
    }
    var HTMLXPreferencesButtonElement: {
        prototype: HTMLXPreferencesButtonElement;
        new (): HTMLXPreferencesButtonElement;
    };
    interface HTMLXPreferencesListElement extends Components.XPreferencesList, HTMLStencilElement {
    }
    var HTMLXPreferencesListElement: {
        prototype: HTMLXPreferencesListElement;
        new (): HTMLXPreferencesListElement;
    };
    interface HTMLXSoundToggleElement extends Components.XSoundToggle, HTMLStencilElement {
    }
    var HTMLXSoundToggleElement: {
        prototype: HTMLXSoundToggleElement;
        new (): HTMLXSoundToggleElement;
    };
    interface HTMLXThemeToggleElement extends Components.XThemeToggle, HTMLStencilElement {
    }
    var HTMLXThemeToggleElement: {
        prototype: HTMLXThemeToggleElement;
        new (): HTMLXThemeToggleElement;
    };
    interface HTMLElementTagNameMap {
        "x-autoplay-toggle": HTMLXAutoplayToggleElement;
        "x-preferences-button": HTMLXPreferencesButtonElement;
        "x-preferences-list": HTMLXPreferencesListElement;
        "x-sound-toggle": HTMLXSoundToggleElement;
        "x-theme-toggle": HTMLXThemeToggleElement;
    }
}
declare namespace LocalJSX {
    interface XAutoplayToggle {
        "autoplay"?: boolean;
    }
    interface XPreferencesButton {
        "icon"?: string;
    }
    interface XPreferencesList {
    }
    interface XSoundToggle {
        "muted"?: boolean;
    }
    interface XThemeToggle {
    }
    interface IntrinsicElements {
        "x-autoplay-toggle": XAutoplayToggle;
        "x-preferences-button": XPreferencesButton;
        "x-preferences-list": XPreferencesList;
        "x-sound-toggle": XSoundToggle;
        "x-theme-toggle": XThemeToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "x-autoplay-toggle": LocalJSX.XAutoplayToggle & JSXBase.HTMLAttributes<HTMLXAutoplayToggleElement>;
            "x-preferences-button": LocalJSX.XPreferencesButton & JSXBase.HTMLAttributes<HTMLXPreferencesButtonElement>;
            "x-preferences-list": LocalJSX.XPreferencesList & JSXBase.HTMLAttributes<HTMLXPreferencesListElement>;
            "x-sound-toggle": LocalJSX.XSoundToggle & JSXBase.HTMLAttributes<HTMLXSoundToggleElement>;
            "x-theme-toggle": LocalJSX.XThemeToggle & JSXBase.HTMLAttributes<HTMLXThemeToggleElement>;
        }
    }
}
