/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ProviderRegistration } from "./services/data-provider/provider-factory";
export namespace Components {
    interface XDataProvider {
        "get": (key: string) => Promise<string>;
        "set": (key: string, value: string) => Promise<void>;
    }
}
declare global {
    interface HTMLXDataProviderElement extends Components.XDataProvider, HTMLStencilElement {
    }
    var HTMLXDataProviderElement: {
        prototype: HTMLXDataProviderElement;
        new (): HTMLXDataProviderElement;
    };
    interface HTMLElementTagNameMap {
        "x-data-provider": HTMLXDataProviderElement;
    }
}
declare namespace LocalJSX {
    interface XDataProvider {
        "onRegister"?: (event: CustomEvent<ProviderRegistration>) => void;
    }
    interface IntrinsicElements {
        "x-data-provider": XDataProvider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "x-data-provider": LocalJSX.XDataProvider & JSXBase.HTMLAttributes<HTMLXDataProviderElement>;
        }
    }
}
